"""Ingest pipeline: discovery, fetch, normalize, media, translate, process."""

from agent_docs.ingest.discover import build_targets, discover_news_urls, extract_links_from_llms
from agent_docs.ingest.fetch import fetch_bytes, fetch_url, http_get, http_get_bytes, test_source_available
from agent_docs.ingest.media import download_images, extract_images, infer_image_ext, rewrite_image_links
from agent_docs.ingest.metadata import write_metadata_block
from agent_docs.ingest.normalize import (
    chinese_ratio,
    count_headings,
    count_links,
    count_tables,
    detect_source_language_by_url,
    extract_main_article_html,
    extract_publication_time,
    extract_title,
    extract_title_from_markdown,
    has_chinese,
    html_to_markdown,
    is_content_too_short,
    is_not_found_text,
    looks_markdown,
    normalize_link,
    normalize_url,
    normalize_url_path,
    parse_frontmatter,
    parse_charset,
    safe_slug,
    strip_frontmatter,
    visible_content_len,
)
from agent_docs.ingest.process import process_target
from agent_docs.ingest.translate import build_translate_prompt, call_translator, pick_preferred_source_url

__all__ = [
    "build_targets",
    "build_translate_prompt",
    "call_translator",
    "chinese_ratio",
    "count_headings",
    "count_links",
    "count_tables",
    "detect_source_language_by_url",
    "discover_news_urls",
    "download_images",
    "extract_images",
    "extract_links_from_llms",
    "extract_main_article_html",
    "extract_publication_time",
    "extract_title",
    "extract_title_from_markdown",
    "fetch_bytes",
    "fetch_url",
    "has_chinese",
    "html_to_markdown",
    "http_get",
    "http_get_bytes",
    "infer_image_ext",
    "is_content_too_short",
    "is_not_found_text",
    "looks_markdown",
    "normalize_link",
    "normalize_url",
    "normalize_url_path",
    "parse_charset",
    "parse_frontmatter",
    "pick_preferred_source_url",
    "process_target",
    "rewrite_image_links",
    "safe_slug",
    "strip_frontmatter",
    "test_source_available",
    "visible_content_len",
    "write_metadata_block",
]
